# Generated by Django 2.1.1 on 2020-02-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=128, verbose_name='MongoDBInst名称')),
                ('inst_host', models.GenericIPAddressField(verbose_name='MongoDBInstIP地址')),
                ('inst_port', models.PositiveIntegerField(verbose_name='MongoDBInst端口')),
                ('manage_user', models.CharField(blank=True, max_length=32, verbose_name='MongoDBInst管理用户')),
                ('manage_userpwd', models.CharField(blank=True, max_length=64, verbose_name='MongoDBInst管理用户密码')),
                ('read_user', models.CharField(blank=True, max_length=32, verbose_name='MongoDBInst只读用户')),
                ('read_userpwd', models.CharField(blank=True, max_length=32, verbose_name='MongoDBInst只读用户密码')),
                ('role', models.CharField(blank=True, choices=[('Master', 'Master'), ('Slave', 'Slave')], default='Master', max_length=12, verbose_name='是否启用')),
                ('services', models.CharField(blank=True, max_length=255, verbose_name='涉及服务')),
                ('version', models.CharField(blank=True, default='3.2.8', max_length=32, verbose_name='MongoDB版本')),
                ('is_enabled', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=12, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'MongoDB实例',
                'verbose_name_plural': 'MongoDB实例',
            },
        ),
        migrations.CreateModel(
            name='MySQLInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=128, verbose_name='MySQLInst名称')),
                ('inst_host', models.GenericIPAddressField(verbose_name='MySQLInstIP地址')),
                ('inst_port', models.PositiveIntegerField(verbose_name='MySQLInst端口')),
                ('manage_user', models.CharField(blank=True, max_length=32, verbose_name='MySQLInst管理用户')),
                ('manage_userpwd', models.CharField(blank=True, max_length=64, verbose_name='MySQLInst管理用户密码')),
                ('read_user', models.CharField(blank=True, max_length=32, verbose_name='MySQLInst只读用户')),
                ('read_userpwd', models.CharField(blank=True, max_length=32, verbose_name='MySQLInst只读用户密码')),
                ('role', models.CharField(blank=True, choices=[('Master', 'Master'), ('Slave', 'Slave')], default='Master', max_length=12, verbose_name='是否启用')),
                ('services', models.CharField(blank=True, max_length=255, verbose_name='涉及服务')),
                ('version', models.CharField(blank=True, default='5.7.21', max_length=32, verbose_name='MYSQL版本')),
                ('is_enabled', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=12, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'MYSQL实例',
                'verbose_name_plural': 'MYSQL实例',
            },
        ),
        migrations.CreateModel(
            name='RedisInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=128, verbose_name='Redis实例')),
                ('inst_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='Redis IP地址')),
                ('inst_port', models.PositiveIntegerField(blank=True, default=3306, null=True, verbose_name='Redis端口')),
                ('password', models.CharField(max_length=64, verbose_name='Redis密码')),
                ('role', models.CharField(blank=True, choices=[('Master', 'Master'), ('Slave', 'Slave')], default='Master', max_length=12, verbose_name='是否启用')),
                ('services', models.CharField(blank=True, max_length=255, verbose_name='涉及服务')),
                ('version', models.CharField(blank=True, default='3.2.0', max_length=32, verbose_name='Redis版本')),
                ('is_enabled', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=12, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Redis实例',
                'verbose_name_plural': 'Redis实例',
            },
        ),
        migrations.CreateModel(
            name='UserAccessMongoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已禁止'), (1, '申请中'), (2, '使用中'), (3, '已驳回')], default=1, verbose_name='用户申请查询权限状态')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('mongodbinst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_mongodbinst', to='db.MongoDBInst', verbose_name='MongoDB实例id')),
            ],
            options={
                'verbose_name': '用户访问MongoDB权限表',
                'verbose_name_plural': '用户访问MongoDB权限表',
            },
        ),
        migrations.CreateModel(
            name='UserAccessMySQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('user_access_db', models.CharField(max_length=64, verbose_name='用户访问数据库')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已禁止'), (1, '申请中'), (2, '使用中'), (3, '已驳回')], default=1, verbose_name='用户申请查询权限状态')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('mysqlinst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_mysqlinst', to='db.MySQLInst', verbose_name='MYSQL实例id')),
            ],
            options={
                'verbose_name': '用户访问MySQL权限表',
                'verbose_name_plural': '用户访问MySQL权限表',
            },
        ),
        migrations.CreateModel(
            name='UserAccessRedis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已禁止'), (1, '申请中'), (2, '使用中'), (3, '已驳回')], default=1, verbose_name='用户申请查询权限状态')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('redisinst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_redisinst', to='db.RedisInst', verbose_name='Redis实例id')),
            ],
            options={
                'verbose_name': '用户访问Redis权限表',
                'verbose_name_plural': '用户访问Redis权限表',
            },
        ),
    ]
