# Generated by Django 2.0.4 on 2019-01-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongodbDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dbname', models.CharField(max_length=128, verbose_name='MongodbDB名称')),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '启用')], verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'MongodbDB',
                'verbose_name_plural': 'MongodbDB',
                'db_table': 'mongodb_dbs',
            },
        ),
        migrations.CreateModel(
            name='MongodbInst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instname', models.CharField(max_length=128, verbose_name='MongodbInst名称')),
                ('host', models.GenericIPAddressField(verbose_name='MongodbInst IP地址')),
                ('port', models.PositiveIntegerField(verbose_name='MongodbInst端口')),
                ('manageuser', models.CharField(max_length=32, verbose_name='MongodbInst管理用户')),
                ('manageuserpwd', models.CharField(max_length=64, verbose_name='MongodbInst管理用户密码')),
                ('readuser', models.CharField(max_length=32, verbose_name='MongodbInst只读用户')),
                ('readuserpwd', models.CharField(max_length=32, verbose_name='MongodbInst只读用户密码')),
                ('version', models.CharField(default=5.7, max_length=32, verbose_name='MYSQL版本')),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '启用')], verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'MongodbInst',
                'verbose_name_plural': 'MongodbInst',
                'db_table': 'mongodb_insts',
            },
        ),
        migrations.AddField(
            model_name='mongodbdb',
            name='mongodbinst_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mongodbinst_id', to='db.MongodbInst', verbose_name='mongodb实例'),
        ),
    ]
