# Generated by Django 2.0.4 on 2020-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongodbinst',
            name='manage_userpwd',
            field=models.CharField(blank=True, max_length=255, verbose_name='MongoDBInst管理用户密码'),
        ),
        migrations.AlterField(
            model_name='mongodbinst',
            name='read_userpwd',
            field=models.CharField(blank=True, max_length=255, verbose_name='MongoDBInst只读用户密码'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='manage_userpwd',
            field=models.CharField(blank=True, max_length=255, verbose_name='MySQLInst管理用户密码'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='read_userpwd',
            field=models.CharField(blank=True, max_length=255, verbose_name='MySQLInst只读用户密码'),
        ),
        migrations.AlterField(
            model_name='redisinst',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Redis密码'),
        ),
    ]
