# Generated by Django 2.0.4 on 2019-06-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqlinst',
            name='commoninfo_ptr',
        ),
        migrations.DeleteModel(
            name='CommonInfo',
        ),
        migrations.DeleteModel(
            name='MySQLInst',
        ),
    ]
