# Generated by Django 2.0.4 on 2019-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongodbdb',
            name='is_enabled',
            field=models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='mongodbinst',
            name='is_enabled',
            field=models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='是否启用'),
        ),
    ]
