# Generated by Django 2.0.4 on 2019-06-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_mysqlinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlinst',
            name='manage_user',
            field=models.CharField(blank=True, max_length=32, verbose_name='MySQLInst管理用户'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='manage_userpwd',
            field=models.CharField(blank=True, max_length=64, verbose_name='MySQLInst管理用户密码'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='read_user',
            field=models.CharField(blank=True, max_length=32, verbose_name='MySQLInst只读用户'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='read_userpwd',
            field=models.CharField(blank=True, max_length=32, verbose_name='MySQLInst只读用户密码'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='role',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Slave', 'Slave')], default='Master', max_length=12, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='services',
            field=models.CharField(blank=True, max_length=255, verbose_name='涉及服务'),
        ),
        migrations.AlterField(
            model_name='mysqlinst',
            name='version',
            field=models.CharField(blank=True, default='5.7.21', max_length=32, verbose_name='MYSQL版本'),
        ),
    ]
