# Generated by Django 2.0.4 on 2019-06-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_useraccessmysql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessmysql',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='useraccessmysql',
            name='life_time',
        ),
        migrations.AlterField(
            model_name='useraccessmysql',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '申请中'), (2, '使用中'), (3, '已禁用')], default=1, verbose_name='用户申请查询权限状态'),
        ),
    ]
