# Generated by Django 2.0.4 on 2019-06-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20190611_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccessmysql',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '已禁止'), (1, '申请中'), (2, '使用中'), (3, '已驳回')], default=1, verbose_name='用户申请查询权限状态'),
        ),
    ]
