# Generated by Django 2.0.4 on 2019-06-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190611_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessmysql',
            name='mysqlinst',
        ),
        migrations.DeleteModel(
            name='UserAccessMySQL',
        ),
    ]
