# Generated by Django 2.0.4 on 2019-07-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20190709_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessmongodb',
            name='user_access_db',
        ),
    ]
