# Generated by Django 2.0.4 on 2019-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_remove_useraccessmongodb_user_access_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=128, verbose_name='Redis实例')),
                ('inst_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='Redis IP地址')),
                ('inst_port', models.PositiveIntegerField(blank=True, default=3306, null=True, verbose_name='Redis端口')),
                ('password', models.CharField(max_length=64, verbose_name='Redis密码')),
                ('role', models.CharField(blank=True, choices=[('Master', 'Master'), ('Slave', 'Slave')], default='Master', max_length=12, verbose_name='是否启用')),
                ('services', models.CharField(blank=True, max_length=255, verbose_name='涉及服务')),
                ('version', models.CharField(blank=True, default='3.2.0', max_length=32, verbose_name='Redis版本')),
                ('is_enabled', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=12, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Redis实例',
                'verbose_name_plural': 'Redis实例',
            },
        ),
        migrations.AlterField(
            model_name='mongodbinst',
            name='version',
            field=models.CharField(blank=True, default='3.2.8', max_length=32, verbose_name='MongoDB版本'),
        ),
    ]
