# Generated by Django 2.0.4 on 2020-04-16 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workorder.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_group_name', models.CharField(blank=True, max_length=128, verbose_name='工单审批组')),
                ('users', models.ManyToManyField(blank=True, related_name='approver_user', to=settings.AUTH_USER_MODEL, verbose_name='审批组内用户')),
            ],
            options={
                'verbose_name': '工单审批组表',
                'verbose_name_plural': '工单审批组表',
            },
        ),
        migrations.CreateModel(
            name='AutoOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, verbose_name='对应工单步骤ID')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工单流转表',
                'verbose_name_plural': '工单流转表',
            },
        ),
        migrations.CreateModel(
            name='AutoOrderStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, verbose_name='步骤id')),
                ('step_name', models.CharField(blank=True, max_length=128, verbose_name='步骤名称')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_step_approvergroup', to='workorder.ApprovalGroup')),
            ],
            options={
                'verbose_name': '工单步骤表',
                'verbose_name_plural': '工单步骤表',
            },
        ),
        migrations.CreateModel(
            name='AutoOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(blank=True, max_length=128, verbose_name='工单类型')),
                ('formconfig', models.TextField(blank=True, verbose_name='form配置')),
                ('remotefuncs', models.TextField(blank=True, verbose_name='工单相关远程方法')),
                ('script', models.CharField(blank=True, max_length=255, verbose_name='执行脚本')),
            ],
            options={
                'verbose_name': '工单类型表',
                'verbose_name_plural': '工单类型表',
            },
        ),
        migrations.CreateModel(
            name='SqlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('sqlfile', models.FileField(storage=workorder.storage.FileStorage(), upload_to='sqlfile/%Y%m%d/', verbose_name='sql文件')),
                ('sqlfilename', models.CharField(blank=True, max_length=255, verbose_name='sql文件名字')),
                ('sqlfileurl', models.CharField(blank=True, max_length=255, verbose_name='sql文件url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SQL文件表',
                'verbose_name_plural': 'SQL文件表',
            },
        ),
        migrations.CreateModel(
            name='SqlOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='操作状态success&error')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SQL工单状态流转表',
                'verbose_name_plural': 'SQL工单状态流转表',
            },
        ),
        migrations.CreateModel(
            name='SqlOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(blank=True, max_length=128, verbose_name='工单类型')),
                ('is_auto', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='DISABLED', max_length=12, verbose_name='是否启用自动执行')),
                ('is_file', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='DISABLED', max_length=12, verbose_name='是否启用附件')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('dba_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_dbaapprover', to='workorder.ApprovalGroup')),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_firstapprover', to='workorder.ApprovalGroup')),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_secondapprover', to='workorder.ApprovalGroup')),
            ],
            options={
                'verbose_name': 'SQL工单类型表',
                'verbose_name_plural': 'SQL工单类型表',
            },
        ),
        migrations.CreateModel(
            name='SqlText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(blank=True, max_length=128, verbose_name='数据库')),
                ('sqltext', models.TextField(blank=True, verbose_name='sql文本')),
                ('sqlstatus', models.IntegerField(choices=[(-1, '已失败'), (0, '待执行'), (1, '已执行')], default=0, verbose_name='SQL状态(inception执行状态)')),
                ('exectime', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
                ('info', models.TextField(blank=True, verbose_name='inception结果')),
                ('instid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqltext_mysqlinst', to='db.MySQLInst')),
            ],
            options={
                'verbose_name': 'SQL文本表',
                'verbose_name_plural': 'SQL文本表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderBase',
            fields=[
                ('workorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='工单主题')),
                ('classify', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('status', models.IntegerField(choices=[(-1, '已失败'), (0, '待审批'), (1, '已驳回'), (2, '已完成'), (3, 'DBA-CHECK'), (4, '待执行'), (5, '已执行，待验证'), (6, '已验证'), (7, '已取消'), (9, '正在处理'), (10, '待接受')], default=0, verbose_name='工单状态')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单基础信息表',
                'verbose_name_plural': '工单基础信息表',
            },
        ),
        migrations.CreateModel(
            name='AutoOrder',
            fields=[
                ('workorderbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='workorder.WorkOrderBase')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='工单参数')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoorder_approvergroup', to='workorder.ApprovalGroup')),
                ('ordertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoorder_type', to='workorder.AutoOrderType')),
            ],
            options={
                'verbose_name': '工单表',
                'verbose_name_plural': '工单表',
            },
            bases=('workorder.workorderbase',),
        ),
        migrations.CreateModel(
            name='SqlOrder',
            fields=[
                ('workorderbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='workorder.WorkOrderBase')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_approvergroup', to='workorder.ApprovalGroup')),
                ('ordertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_type', to='workorder.SqlOrderType')),
            ],
            options={
                'verbose_name': 'SQL工单表',
                'verbose_name_plural': 'SQL工单表',
            },
            bases=('workorder.workorderbase',),
        ),
        migrations.AddField(
            model_name='autoorderstep',
            name='ordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertype_step', to='workorder.AutoOrderType'),
        ),
        migrations.AddField(
            model_name='sqltext',
            name='sqlorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_sqltext', to='workorder.SqlOrder'),
        ),
        migrations.AddField(
            model_name='sqlorderstate',
            name='sqlorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_state', to='workorder.SqlOrder'),
        ),
        migrations.AddField(
            model_name='sqlfile',
            name='sqlorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_sqlfile', to='workorder.SqlOrder'),
        ),
        migrations.AddField(
            model_name='autoorderstate',
            name='autoorder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_autoorder_id', to='workorder.AutoOrder', verbose_name='工单id'),
        ),
    ]
