# Generated by Django 2.1.1 on 2020-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderbase',
            name='status',
            field=models.IntegerField(choices=[(-1, '已失败'), (0, '待审批'), (1, '已驳回'), (2, '已完成'), (3, 'DBA-CHECK'), (4, '待执行'), (5, '已执行，待验证'), (6, '已验证'), (7, '已取消'), (8, '未接受'), (9, '正在处理')], default=0, verbose_name='工单状态'),
        ),
    ]
