# Generated by Django 2.0.4 on 2019-12-31 07:51

from django.db import migrations, models
import django.db.models.deletion
import sqlorder.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0011_workordertype_remotefuncs'),
        ('db', '0015_useraccessredis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('sqlfile', models.FileField(storage=sqlorder.storage.FileStorage(), upload_to='sqlfile/%Y%m%d/', verbose_name='sql文件')),
                ('sqlfilename', models.CharField(blank=True, max_length=255, verbose_name='sql文件名字')),
                ('sqlfileurl', models.CharField(blank=True, max_length=255, verbose_name='sql文件url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SQL文件表',
                'verbose_name_plural': 'SQL文件表',
            },
        ),
        migrations.CreateModel(
            name='SqlOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='工单名称')),
                ('status', models.IntegerField(choices=[(-1, '已失败'), (0, '待审批'), (1, '已驳回'), (2, '已完成'), (3, 'DBA-CHECK'), (4, '待执行'), (5, '已执行，待验证'), (6, '已验证'), (7, '已取消')], default=0, verbose_name='工单状态')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_approvergroup', to='workflow.ApprovalGroup')),
            ],
            options={
                'verbose_name': 'SQL工单表',
                'verbose_name_plural': 'SQL工单表',
            },
        ),
        migrations.CreateModel(
            name='SqlOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='操作状态success&error')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sqlorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_state', to='sqlorder.SqlOrder')),
            ],
            options={
                'verbose_name': 'SQL工单状态流转表',
                'verbose_name_plural': 'SQL工单状态流转表',
            },
        ),
        migrations.CreateModel(
            name='SqlOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(blank=True, max_length=128, verbose_name='工单类型')),
                ('is_auto', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='DISABLED', max_length=12, verbose_name='是否启用自动执行')),
                ('is_file', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='DISABLED', max_length=12, verbose_name='是否启用附件')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('dba_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_dbaapprover', to='workflow.ApprovalGroup')),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_firstapprover', to='workflow.ApprovalGroup')),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_secondapprover', to='workflow.ApprovalGroup')),
            ],
            options={
                'verbose_name': 'SQL工单类型表',
                'verbose_name_plural': 'SQL工单类型表',
            },
        ),
        migrations.CreateModel(
            name='SqlText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(blank=True, max_length=128, verbose_name='数据库')),
                ('sqltext', models.TextField(blank=True, verbose_name='sql文本')),
                ('sqlstatus', models.IntegerField(choices=[(-1, '已失败'), (0, '待执行'), (1, '已执行')], default=0, verbose_name='SQL状态(inception执行状态)')),
                ('exectime', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
                ('info', models.TextField(blank=True, verbose_name='inception结果')),
                ('instid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqltext_mysqlinst', to='db.MySQLInst')),
                ('sqlorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_sqltext', to='sqlorder.SqlOrder')),
            ],
            options={
                'verbose_name': 'SQL文本表',
                'verbose_name_plural': 'SQL文本表',
            },
        ),
        migrations.AddField(
            model_name='sqlorder',
            name='ordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sqlorder_type', to='sqlorder.SqlOrderType'),
        ),
        migrations.AddField(
            model_name='sqlfile',
            name='sqlorder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqlorder_sqlfile', to='sqlorder.SqlOrder'),
        ),
    ]
