# Generated by Django 2.0.4 on 2020-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpWhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_user', models.CharField(blank=True, max_length=64, unique=True, verbose_name='白名单用户')),
                ('white_table', models.TextField(blank=True, verbose_name='白名单')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导出白名单表',
                'verbose_name_plural': '导出白名单表',
            },
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_host', models.CharField(blank=True, max_length=64, verbose_name='邮箱服务器')),
                ('mail_port', models.IntegerField(blank=True, default=25, verbose_name='邮箱服务器端口')),
                ('mail_user', models.CharField(blank=True, max_length=32, verbose_name='邮箱用户')),
                ('mail_pass', models.CharField(blank=True, max_length=32, verbose_name='邮箱用户密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '邮件配置',
                'verbose_name_plural': '邮件配置',
            },
        ),
        migrations.CreateModel(
            name='QueryLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(blank=True, max_length=64, verbose_name='查询类型')),
                ('query_limit', models.IntegerField(blank=True, default=25, verbose_name='查询LIMIT')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '查询limit配置',
                'verbose_name_plural': '查询limit配置',
            },
        ),
    ]
