# Generated by Django 2.0.4 on 2020-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailconfig',
            name='mail_pass',
            field=models.CharField(blank=True, max_length=255, verbose_name='邮箱用户密码'),
        ),
    ]
