# Generated by Django 2.0.4 on 2019-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20190516_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailconfig',
            name='comment',
            field=models.CharField(blank=True, max_length=64, verbose_name='备注'),
        ),
    ]
