# Generated by Django 2.0.4 on 2019-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_mailconfig_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailconfig',
            name='mail_port',
            field=models.IntegerField(blank=True, default=25, verbose_name='邮箱服务器端口'),
        ),
    ]
