# Generated by Django 2.0.4 on 2019-05-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_auto_20190516_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_uri', models.CharField(blank=True, max_length=128, verbose_name='ldap服务器地址')),
                ('ldap_base_dn', models.IntegerField(blank=True, default=128, verbose_name='ldap服务base_dn')),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=128, verbose_name='ldap服务bind_dn')),
                ('ldap_bind_passwd', models.CharField(blank=True, max_length=128, verbose_name='ldap服务bind_dn_passwd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'LDAP配置',
                'verbose_name_plural': 'LDAP配置',
            },
        ),
    ]
