# Generated by Django 2.0.4 on 2019-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_ldapconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconfig',
            name='ldap_base_dn',
            field=models.CharField(blank=True, max_length=128, verbose_name='ldap服务base_dn'),
        ),
    ]
