# Generated by Django 2.0.4 on 2019-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0008_querylimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpWhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_user', models.CharField(blank=True, max_length=64, verbose_name='白名单用户')),
                ('white_table', models.TextField(blank=True, verbose_name='白名单')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '导出白名单表',
                'verbose_name_plural': '导出白名单表',
            },
        ),
    ]
