# Generated by Django 2.0.4 on 2019-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0010_remove_dumpwhitelist_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpwhitelist',
            name='white_user',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='白名单用户'),
        ),
    ]
