# Generated by Django 2.0.4 on 2019-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0011_auto_20190703_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=64, verbose_name='url名称')),
                ('url_address', models.TextField(blank=True, verbose_name='url地址')),
                ('url_conf', models.CharField(blank=True, max_length=255, verbose_name='url对应配置文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '线上url列表',
                'verbose_name_plural': '线上url列表',
            },
        ),
    ]
