# Generated by Django 2.0.4 on 2019-08-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0012_onlineurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUrl',
        ),
    ]
