# Generated by Django 2.0.4 on 2019-08-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formconfig', models.TextField(blank=True, verbose_name='form配置')),
            ],
            options={
                'verbose_name': '工单Form表',
                'verbose_name_plural': '工单Form表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, verbose_name='步骤id')),
            ],
            options={
                'verbose_name': '工单步骤表',
                'verbose_name_plural': '工单步骤表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(blank=True, max_length=128, verbose_name='工单类型')),
                ('script', models.CharField(blank=True, max_length=255, verbose_name='执行脚本')),
            ],
            options={
                'verbose_name': '工单类型表',
                'verbose_name_plural': '工单类型表',
            },
        ),
        migrations.AddField(
            model_name='workorderstep',
            name='ordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertype_step', to='workflow.WorkOrderType'),
        ),
        migrations.AddField(
            model_name='workorderform',
            name='ordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertype_form', to='workflow.WorkOrderType'),
        ),
    ]
