# Generated by Django 2.0.4 on 2019-07-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='主题')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已终止'), (1, '申请中'), (2, '已同意'), (3, '已驳回')], default=1, verbose_name='工单状态')),
                ('git_user', models.CharField(max_length=50, verbose_name='git账户')),
                ('git_project', models.CharField(max_length=255, verbose_name='git项目')),
                ('git_permission', models.CharField(max_length=255, verbose_name='git权限')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='创建人')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工单表',
                'verbose_name_plural': '工单表',
            },
        ),
        migrations.CreateModel(
            name='GitWorkOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('gitwordorder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_gitwordorder_id', to='workflow.GitWorkOrder', verbose_name='Git工单id')),
            ],
            options={
                'verbose_name': '工单流转表',
                'verbose_name_plural': '工单流转表',
            },
        ),
    ]
