# Generated by Django 2.0.4 on 2019-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitworkorder',
            name='describe',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
