# Generated by Django 2.0.4 on 2019-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderform',
            name='ordertype',
        ),
        migrations.AddField(
            model_name='workordertype',
            name='formconfig',
            field=models.TextField(blank=True, verbose_name='form配置'),
        ),
        migrations.DeleteModel(
            name='WorkOrderForm',
        ),
    ]
