# Generated by Django 2.0.4 on 2019-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_gitworkorder_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitworkorder',
            name='operation_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='操作组'),
        ),
    ]
