# Generated by Django 2.0.4 on 2019-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_gitworkorder_operation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitworkorder',
            name='workorder_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='工单号'),
        ),
    ]
