# Generated by Django 2.0.4 on 2019-08-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_approvalgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalgroup',
            old_name='user',
            new_name='users',
        ),
    ]
