# Generated by Django 2.0.4 on 2019-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_gitworkorder_workorder_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitworkorder',
            name='workorder_num',
        ),
        migrations.AddField(
            model_name='gitworkorder',
            name='order_prefix',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='工单号前缀'),
        ),
    ]
