# Generated by Django 2.0.4 on 2019-08-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190828_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderstep',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_step_approvergroup', to='workflow.ApprovalGroup'),
        ),
    ]
