# Generated by Django 2.0.4 on 2019-07-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190722_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitworkorder',
            name='git_project',
            field=models.TextField(blank=True, verbose_name='git项目'),
        ),
    ]
