# Generated by Django 2.0.4 on 2019-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workorderstep_approver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderstep',
            name='step_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='步骤名称'),
        ),
    ]
