# Generated by Django 2.0.4 on 2019-08-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workordertype_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertype',
            name='steps',
        ),
    ]
