# Generated by Django 2.0.4 on 2019-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190723_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderstate',
            name='step',
            field=models.IntegerField(blank=True, default=1, verbose_name='步骤'),
            preserve_default=False,
        ),
    ]
