# Generated by Django 2.0.4 on 2019-08-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_remove_workordertype_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderstep',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_step_approvergroup', to='workflow.ApprovalGroup'),
        ),
    ]
