# Generated by Django 2.0.4 on 2019-08-30 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20190830_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='工单主题')),
                ('status', models.IntegerField(choices=[(-1, '已失败'), (0, '已终止'), (1, '审批中'), (2, '已同意'), (3, '已完成'), (4, '已驳回')], default=1, verbose_name='工单状态')),
                ('content', models.TextField(blank=True, verbose_name='工单参数')),
                ('creator', models.CharField(blank=True, max_length=50, verbose_name='申请人')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_approvergroup', to='workflow.ApprovalGroup')),
                ('ordertype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_type', to='workflow.WorkOrderType')),
            ],
            options={
                'verbose_name': '工单表',
                'verbose_name_plural': '工单表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, verbose_name='对应工单步骤ID')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('wordorder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_wordorder_id', to='workflow.WorkOrder', verbose_name='工单id')),
            ],
            options={
                'verbose_name': '工单流转表',
                'verbose_name_plural': '工单流转表',
            },
        ),
    ]
