# Generated by Django 2.0.4 on 2019-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_workorder_workorderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertype',
            name='remotefuncs',
            field=models.TextField(blank=True, verbose_name='工单相关远程方法'),
        ),
    ]
