# Generated by Django 2.0.4 on 2019-06-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20190604_1601'),
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessmysql',
            name='mysqlinst_id',
        ),
        migrations.AddField(
            model_name='useraccessmysql',
            name='mysqlinst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_access_mysqlinst', to='db.MySQLInst', verbose_name='MYSQL实例id'),
        ),
    ]
