# Generated by Django 2.0.4 on 2019-06-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_auto_20190605_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessmysql',
            name='mysqlinst',
        ),
        migrations.DeleteModel(
            name='UserAccessMySQL',
        ),
    ]
