# Generated by Django 3.0.6 on 2020-05-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySqlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=64, null=True, verbose_name='查询人')),
                ('dbname', models.CharField(blank=True, max_length=64, null=True, verbose_name='查询数据库')),
                ('sql', models.TextField(blank=True, verbose_name='查询sql')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
                ('mysqlinst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='querysqllog_mysqlinst', to='db.MySQLInst', verbose_name='查询实例')),
            ],
            options={
                'verbose_name': 'sql查询日志表',
                'verbose_name_plural': 'sql查询日志表',
            },
        ),
    ]
