# Generated by Django 2.0.4 on 2019-04-17 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsgroup',
            options={'verbose_name': '权限组', 'verbose_name_plural': '权限组'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('dd25a9a0-aa7a-47e1-be59-a7c263ce3586'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AlterModelTable(
            name='permissionsgroup',
            table='permissionsGroup',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='usergroup',
        ),
    ]
