# Generated by Django 2.0.4 on 2020-04-16 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('7b3745a8-727b-4e3f-af82-62041121b705'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
