# Generated by Django 2.0.4 on 2019-08-13 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=255, verbose_name='对应前端组件名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('0f4cca00-bd6f-443b-acfe-94f61098f33a'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
