# Generated by Django 2.1.1 on 2020-02-21 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('2df7d766-c715-40de-8471-1ebc12542b7e'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
