# Generated by Django 3.0.6 on 2020-05-08 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('4ddcb039-acbe-40be-aa09-fa4358023c75'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
