# Generated by Django 2.0.4 on 2020-04-16 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200416_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('fa9c47cb-74e6-4dd5-858f-80313ed382e8'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
