# Generated by Django 3.0.6 on 2020-05-08 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200508_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('6068ce03-3e92-4905-a4df-1c3c0260dc7f'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
