# Generated by Django 2.0.4 on 2019-04-17 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190417_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('ed7c8388-8cd4-4087-a948-d8c94b15a37d'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AlterModelTable(
            name='permissionsgroup',
            table='permissionsgroup',
        ),
    ]
