# Generated by Django 2.0.4 on 2018-11-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181130_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
