# Generated by Django 2.0.4 on 2019-08-20 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190816_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('5ea55f4b-05d0-4ce3-9cf4-8d7debc6da77'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_role', to='user.Role', verbose_name='拥有的所有角色'),
        ),
    ]
