# Generated by Django 2.0.4 on 2020-04-17 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200416_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('793f58c8-612e-4636-8670-37ffcb1537ea'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
