# Generated by Django 2.0.4 on 2020-03-03 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a3450a5c-43b9-46aa-879c-02ff49aae697'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
