# Generated by Django 2.0.4 on 2019-04-17 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190417_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('35572bef-e682-4148-b409-a0d4062f2e59'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
