# Generated by Django 2.0.4 on 2020-03-03 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200303_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('04450140-a64e-4f7e-90cf-9ddbaa3dad34'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
