# Generated by Django 3.0.6 on 2020-05-08 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200508_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('5faa7570-cad4-4b43-b3c2-1b66d031cb08'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
