# Generated by Django 2.0.4 on 2019-05-16 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190417_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('8f7b20d9-a2aa-4bea-93d6-af1b8222464a'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AlterModelTable(
            name='permissionsgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
