# Generated by Django 2.0.4 on 2019-05-16 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190516_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('86ac7b65-6e39-4550-8b84-70f155f94ea8'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
