# Generated by Django 2.0.4 on 2020-03-03 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200303_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('10bd2749-0f1d-4f8d-a3a7-d002cd3e40fb'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
