# Generated by Django 2.0.4 on 2018-12-05 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_users_jwt_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('accessdblist', models.CharField(max_length=500, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('0ec4e888-6f4a-428d-a6d9-4c9d9d4b7a30'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
