# Generated by Django 2.0.4 on 2018-12-07 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181205_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccessDb',
        ),
        migrations.AddField(
            model_name='users',
            name='accessdb',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='可访问数据库'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('83da0f32-1a8b-4fff-9a6b-270f175c4131'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
