# Generated by Django 2.0.4 on 2019-08-27 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190827_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('9bf52c2d-f90a-4792-a407-f18eaa90b563'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
