# Generated by Django 2.0.4 on 2019-05-16 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190516_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a6c03298-679a-4035-8d37-1ebe0f45ce1a'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
