# Generated by Django 2.0.4 on 2020-03-03 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200303_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('79e57b4b-a6b6-4013-8441-76c8ed85ebc2'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
