# Generated by Django 2.0.4 on 2020-03-03 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200303_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('51d2fd1c-8498-46a9-be39-800333a8f2e3'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
