# Generated by Django 2.0.4 on 2019-08-28 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190827_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('4e1f35c5-f520-47c7-8423-939c855205b5'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
