# Generated by Django 3.0.6 on 2020-05-14 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200514_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('5686cff1-898b-474f-95ac-0115a898a78f'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
