# Generated by Django 2.0.4 on 2018-12-07 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181207_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('b7c1f7d1-a5f4-4434-9ae2-8c97b24ae3e9'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
