# Generated by Django 2.0.4 on 2019-05-16 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190516_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('35b2b3f4-f610-4b22-8770-37b544b2a8c7'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
