# Generated by Django 2.0.4 on 2019-08-28 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190828_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('7dfbb28e-0b18-42f2-9e0c-1f1e6dab4413'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
