# Generated by Django 2.0.4 on 2019-05-16 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190516_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('b5fecb0d-607e-496b-8d64-977bcde74cf0'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
