# Generated by Django 2.0.4 on 2020-03-09 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200303_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='api',
            field=models.CharField(blank=True, max_length=255, verbose_name='后端api接口地址'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mtype',
            field=models.IntegerField(blank=True, verbose_name='菜单类型 0:目录 1:菜单 2:权限 3:内部跳转url'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='perms',
            field=models.CharField(blank=True, max_length=255, verbose_name='授权(多个用逗号分隔，如sys:user:post,sys:user:patch)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('70490f1b-e537-48b5-a85d-338ed0556221'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
