# Generated by Django 2.0.4 on 2020-03-09 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200309_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a6cbf891-e8f4-454b-8894-999199369db8'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
