# Generated by Django 2.0.4 on 2018-12-07 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181207_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accessdb',
            field=models.CharField(blank=True, max_length=500, verbose_name='可访问数据库'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('aa7ef4a6-beb6-46b2-988c-709637842afb'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
