# Generated by Django 2.0.4 on 2019-05-30 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190524_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='user_group_join', to='user.UserGroup'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('df451460-e4b5-46f3-ba9f-109a80a63bb6'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AlterField(
            model_name='users',
            name='permissions_group',
            field=models.ManyToManyField(blank=True, related_name='user_permissions_join', to='user.PermissionsGroup'),
        ),
    ]
