# Generated by Django 2.0.4 on 2019-08-29 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190828_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('13dcfeeb-f2fc-48ac-9893-97fdd4336cf6'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
