# Generated by Django 2.0.4 on 2020-03-09 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200309_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, max_length=255, verbose_name='后端api接口地址')),
                ('perms', models.CharField(blank=True, max_length=255, verbose_name='授权(多个用逗号分隔，如sys:user:post,sys:user:patch)')),
                ('creator', models.CharField(blank=True, max_length=64, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, max_length=64, verbose_name='最后修改人')),
                ('del_flag', models.IntegerField(blank=True, verbose_name='是否删除 -1:删除 0:正常')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(blank=True, max_length=64, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='mtype',
            field=models.IntegerField(blank=True, verbose_name='菜单类型 0:目录 1:菜单 2:内部跳转url '),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('c02b623e-6323-4f6f-85bb-bce6cdfa5b64'), verbose_name='用户jwt加密秘钥'),
        ),
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.ManyToManyField(blank=True, related_name='role_perms', to='user.Perms'),
        ),
    ]
