# Generated by Django 2.0.4 on 2018-12-07 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181207_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='webcat',
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a2d02fda-a473-40e5-90ca-b3aca56b473b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
