# Generated by Django 2.0.4 on 2018-12-07 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181207_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='comment',
            field=models.CharField(blank=True, max_length=64, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='users',
            name='webcat',
            field=models.CharField(blank=True, max_length=120, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('88ef7edf-6a98-466e-9770-693dec61753b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
