# Generated by Django 2.0.4 on 2019-08-29 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190829_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('66dffa4d-1587-46d3-90ac-71043111508e'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
