# Generated by Django 2.0.4 on 2019-05-30 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190530_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('0fdcbcde-cdc6-45e2-86d8-6fde8af12341'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
