# Generated by Django 2.0.4 on 2020-03-09 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200309_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='perms',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='后端api名称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('822230e1-820b-449d-a3f4-fb61f713a9b2'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
