# Generated by Django 2.0.4 on 2018-12-07 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181207_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('094baafc-5d5f-4c34-8dda-a517efeb7ed8'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
