# Generated by Django 2.0.4 on 2019-08-29 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190829_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('84279b51-f436-4d39-b5b1-89e8421d6201'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
