# Generated by Django 2.0.4 on 2019-05-31 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190531_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('2bad2ba2-c6e0-4638-ba09-6341a2638a49'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
