# Generated by Django 2.0.4 on 2019-01-21 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181207_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('70703e77-6756-42ae-b3f2-3c0489c82eb7'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
