# Generated by Django 2.0.4 on 2020-03-09 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200309_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perms',
            name='perms',
        ),
        migrations.AddField(
            model_name='perms',
            name='api_type',
            field=models.CharField(blank=True, max_length=12, verbose_name='后端api接口类型: get，post，patch，deletel'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('3c1a7469-b32b-4103-a80e-2fbe3b514084'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
