# Generated by Django 2.0.4 on 2020-03-09 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200309_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('873e2345-51e8-4af1-a04d-c47f4b7069ad'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
