# Generated by Django 2.0.4 on 2019-08-30 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190830_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('ef6abaef-5e77-4cb3-bc61-ad26fccbc264'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
