# Generated by Django 2.0.4 on 2019-05-31 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190531_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('bc793b83-6bec-4f89-a9ba-c8afa75b61f0'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
