# Generated by Django 2.0.4 on 2019-01-21 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('4c6f53ce-cbd1-4ed5-824b-308dc9b4bcef'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
