# Generated by Django 2.0.4 on 2019-06-03 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190531_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('5cfff23a-74b6-4e7a-afd9-86c76fa37c72'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
