# Generated by Django 2.0.4 on 2019-03-11 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('1a80975d-98b6-4e82-86a9-ef6346081bbb'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
