# Generated by Django 2.0.4 on 2020-03-09 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200309_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perms',
            name='api_type',
        ),
        migrations.AddField(
            model_name='perms',
            name='perms',
            field=models.CharField(blank=True, max_length=255, verbose_name='授权(多个用逗号分隔，如sys:user:post,sys:user:patch)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('d9eca020-8ab5-4dd4-8226-7d59c5b38dba'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
