# Generated by Django 2.0.4 on 2019-09-03 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190830_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('6516e34b-3731-4e0f-8336-1923b25c438b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
