# Generated by Django 2.0.4 on 2019-03-14 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190311_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('de8fa83c-e6ef-4d3c-bc7e-4dffb195e221'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
