# Generated by Django 2.0.4 on 2019-06-03 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190603_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('80505874-9a3c-4c66-86f1-41cb9ae7a3a9'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
