# Generated by Django 2.0.4 on 2020-03-09 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200309_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perms',
            name='perms',
            field=models.CharField(blank=True, max_length=255, verbose_name='授权(多个用逗号分隔，如sys:user:post,sys:user:patch)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('8ddf4248-6471-4708-9d4d-bc7e9fbd9bad'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
