# Generated by Django 2.0.4 on 2019-12-10 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20191210_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a8537bc4-1a49-4531-adb3-51b88ec9cee6'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
