# Generated by Django 2.0.4 on 2019-03-14 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190314_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('8112ee77-fa9c-4e46-8bc3-94b06e4ee87a'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
