# Generated by Django 2.0.4 on 2019-06-03 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190603_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('076acd3c-dc6d-485f-ae9c-b34fd8b253b4'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
