# Generated by Django 2.0.4 on 2019-12-12 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20191210_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('9304c444-d56d-4337-ab0b-7b3b91727b3e'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
