# Generated by Django 2.0.4 on 2019-06-03 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190603_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('4b66dff3-6825-419d-9bcc-03c6f4983424'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
