# Generated by Django 2.0.4 on 2019-03-14 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190314_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('618c3578-1185-4ce5-a3d4-581eff1897c9'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
