# Generated by Django 2.0.4 on 2019-06-03 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190603_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('c59e5312-bf2b-4f3d-9e0f-329aa536c485'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
