# Generated by Django 2.0.4 on 2019-12-13 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20191212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('e07db366-0f53-4108-a292-a0feeac8ecf0'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
