# Generated by Django 2.0.4 on 2019-12-18 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20191213_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('6b339612-789a-469d-b590-5ad0b2774d93'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
