# Generated by Django 2.0.4 on 2019-06-04 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190603_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('bfc50bca-2509-4462-bbc5-dd86e1ce6466'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
