# Generated by Django 2.0.4 on 2019-06-05 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190604_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('8452714e-5771-435a-9a8a-c9102aca62ed'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
