# Generated by Django 2.0.4 on 2019-12-19 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20191218_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('51d8cfe7-a96d-4d1b-afbe-eb9603e761fa'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
