# Generated by Django 2.0.4 on 2019-06-05 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190605_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('0e1e540e-a764-499e-a885-5dac50cb74fc'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
