# Generated by Django 2.0.4 on 2019-06-05 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190605_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('7080545f-3e85-456e-8086-22aa9f241eb7'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
