# Generated by Django 2.0.4 on 2019-12-19 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20191219_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('dd9ecdc6-0a0d-4675-83a0-809f64afd483'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
