# Generated by Django 2.0.4 on 2019-06-11 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190605_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('ccbd08b9-5394-46a2-af35-fbda3d053cf9'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
