# Generated by Django 2.0.4 on 2019-12-26 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20191220_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a5ba4ded-fa84-4111-8ae9-2cd0bee9234b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
