# Generated by Django 2.0.4 on 2019-06-11 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20190611_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('103cef98-2ade-46ff-bdb9-927a07c2940e'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
