# Generated by Django 2.0.4 on 2019-06-13 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190611_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('9cbe5fa4-dca4-44a5-93b6-d80e9d339e92'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
