# Generated by Django 2.0.4 on 2019-12-26 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20191226_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('15c08285-7bb2-4c56-9ef6-12c91b5c85c5'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
