# Generated by Django 2.0.4 on 2019-06-13 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20190613_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('332e160b-03e0-4a0f-9742-d74bc1f1e025'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
