# Generated by Django 2.0.4 on 2019-12-27 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20191226_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a0bf4a79-7483-4a45-b2a7-23353e4c8c72'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
