# Generated by Django 2.0.4 on 2019-06-13 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20190613_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('774f8429-5d85-4cdb-b7ff-de377f97c168'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
