# Generated by Django 2.0.4 on 2019-06-24 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20190613_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('c6df474f-f765-4588-a3df-5201636cc640'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
