# Generated by Django 2.0.4 on 2019-12-27 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20191227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('7ec03911-3646-492b-b200-9e77439eb94c'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
