# Generated by Django 2.0.4 on 2019-12-30 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20191227_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('14b02192-86d0-4278-9da4-a1819250acb4'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
