# Generated by Django 2.0.4 on 2019-07-02 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190624_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('6b100523-1f9b-4391-80d5-d65a3893e1ae'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
