# Generated by Django 2.0.4 on 2019-12-30 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20191230_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('ae58543c-73a6-4dd6-80f7-e65dfed8e015'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
