# Generated by Django 2.0.4 on 2019-07-03 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20190702_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('3fa47ede-f718-4153-bef7-20c54db237b4'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
