# Generated by Django 2.0.4 on 2019-12-30 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20191230_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a3e5c33d-3f82-42d0-b82d-76f136f75f25'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
