# Generated by Django 2.0.4 on 2019-12-30 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20191230_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('09c2aa75-3870-4c20-888b-02da9b3f524d'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
