# Generated by Django 2.0.4 on 2019-07-04 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20190703_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a6b82465-4979-42cb-afc8-d1d991e44dd5'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
