# Generated by Django 2.0.4 on 2019-07-08 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20190704_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('17b74664-fba2-4ff3-89de-3e94e0153dde'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
