# Generated by Django 2.0.4 on 2019-07-09 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20190708_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('2921e798-876e-4147-ab0f-bd349c42919d'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
