# Generated by Django 2.0.4 on 2019-12-30 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20191230_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('afb6814c-31b7-401a-867f-188899acabab'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
