# Generated by Django 2.0.4 on 2019-12-30 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20191230_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('5e7a7b7f-3ac4-4c26-b3ea-0bf712cb2696'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
