# Generated by Django 2.0.4 on 2019-07-09 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20190709_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('c1d14d46-b166-4953-aeb9-c5ae74bc9826'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
