# Generated by Django 2.0.4 on 2019-12-30 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20191230_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('b61437b2-b1b9-4342-9a9b-b27e7dfdc044'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
