# Generated by Django 2.0.4 on 2019-07-15 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20190709_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('16d2228e-e501-433e-b6b7-705520d2236b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
