# Generated by Django 2.0.4 on 2019-07-18 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20190716_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('b51bef92-d207-4971-b95e-6d4b02292c6b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
