# Generated by Django 2.0.4 on 2019-12-30 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20191230_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('3edbd31d-9112-4815-944f-714905b9d4b7'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
