# Generated by Django 2.0.4 on 2019-07-19 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20190718_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('9e237f07-88ae-4356-9d17-d32bbdb10a18'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
