# Generated by Django 2.0.4 on 2019-07-19 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20190719_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('0408d66c-9ff9-476d-b4a2-c9fda2c7f182'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
