# Generated by Django 2.0.4 on 2019-12-30 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20191230_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('30ea87d8-893c-4315-aad3-b85845efdaea'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
