# Generated by Django 2.0.4 on 2019-07-22 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20190719_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('705ed42a-33d1-4a91-92fd-e2f37f964471'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
