# Generated by Django 2.0.4 on 2019-12-30 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20191230_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('42689736-e64d-4da0-bc94-84d94900ac8a'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
