# Generated by Django 2.0.4 on 2019-07-22 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20190722_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('38b051bd-5616-41e9-ac5a-4b5a3fbf52a1'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
