# Generated by Django 2.0.4 on 2019-12-31 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20191230_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('d32ea26a-66ba-46d1-baf7-b14e036a19c1'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
