# Generated by Django 2.0.4 on 2019-07-23 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20190722_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('985d51a7-dd1d-4cfd-b662-1c751e5a43f0'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
