# Generated by Django 2.0.4 on 2019-12-31 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20191231_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('e2575bd8-7bd5-49b9-975d-eb4eb1021cfa'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
