# Generated by Django 2.0.4 on 2019-12-31 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20191231_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('50932feb-1a73-416c-b63d-d02420f05e2b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
