# Generated by Django 2.0.4 on 2019-12-31 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20191231_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('02ae774d-50c8-43a5-8584-9b26ac791f73'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
