# Generated by Django 2.0.4 on 2019-07-25 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20190724_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('a89dcf40-c3c6-4734-9131-e2f72f75f545'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
