# Generated by Django 2.0.4 on 2019-12-31 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20191231_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('069da995-3595-4103-ae54-4c897aa7829b'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
