# Generated by Django 2.0.4 on 2019-07-25 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20190725_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.UUID('4de65c17-f871-4aad-828f-1001fa5b4c04'), verbose_name='用户jwt加密秘钥'),
        ),
    ]
